/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizador;

import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import jdk.nashorn.internal.parser.Lexer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Analizer extends javax.swing.JFrame {

    /**
     * Creates new form Analizer
     */
    public Analizer() {
        initComponents();
        /*
        token.addColumn("TOKEN");
	token.addColumn("LEXEMA");
	token.addColumn("CADENA");
	token.addColumn("LINEA");
	token.addColumn("COLUMNA");
	try{
		//Lexer.Analizer.Tabla1.setModel(token);
	}catch(Exception ex){
		JOptionPane.showMessageDialog(this, "Se recomienda analizar la tabla", "ADVERTENCIA!!", JOptionPane.WARNING_MESSAGE);
	}
	setLocationRelativeTo(null);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        epscript = new javax.swing.JEditorPane();
        btnarchivoevaluado = new javax.swing.JButton();
        btnreporte = new javax.swing.JButton();
        btncargararchivo = new javax.swing.JButton();
        txt_path = new javax.swing.JTextField();
        btnrecargar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        txt_filtro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        jScrollPane2.setViewportView(epscript);

        btnarchivoevaluado.setText("ARCHIVO EVALUDADO");
        btnarchivoevaluado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarchivoevaluadoActionPerformed(evt);
            }
        });

        btnreporte.setText("REPORTE");
        btnreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteActionPerformed(evt);
            }
        });

        btncargararchivo.setText("LIMPIAR");
        btncargararchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargararchivoActionPerformed(evt);
            }
        });

        txt_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pathActionPerformed(evt);
            }
        });

        btnrecargar.setText("ABRIR");
        btnrecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecargarActionPerformed(evt);
            }
        });

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        txt_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filtroActionPerformed(evt);
            }
        });
        txt_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_filtroKeyTyped(evt);
            }
        });

        jLabel1.setText("BUSQUEDA");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnrecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_path))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnarchivoevaluado, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btncargararchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_path, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnarchivoevaluado, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btnreporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncargararchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecargarActionPerformed
        Object[]  obj = {"lslkjd", 8099, 89.2, "sdlk"};
    DefaultTableModel model;
        model = (DefaultTableModel) Tabla1.getModel();
    try{
            JFileChooser abrir = new JFileChooser();
            String cadena = "";
            String texto = "";
            String direccion = "";
            abrir.setFileSelectionMode(JFileChooser.FILES_ONLY);
	
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("txt","txt","txt");
            abrir.setFileFilter(filtro);
            
            try {
                int selecciona = abrir.showDialog(abrir, direccion);
		String path = abrir.getSelectedFile().getParent() + "/" +abrir.getSelectedFile().getName();
		direccion = path;
		if (selecciona == JFileChooser.APPROVE_OPTION){
                    try{
                        File archivo = new File(path);
                        FileReader lector = new FileReader(archivo);
				
			BufferedReader leer = new BufferedReader (new InputStreamReader (new FileInputStream(path), "ISO-8859-1"));
			String linea = "";
			int lin = 00;
			while ((linea = leer.readLine())!= null){
				cadena += linea + "\n";
			}
				leer.close();
				cadena = cadena.replace("ï¤¿","");
				cadena = cadena.replace("Ã©","é");
				cadena = cadena.replace("Ã°","ú");
				cadena = cadena.replace("Ä-","í");
				cadena = cadena.replace("Ä'","ó");
				cadena = cadena.replace("Ãi","á");
					
                                txt_path.setText(archivo.getAbsolutePath());	
                        
                    }catch(Exception e){                       
                        
                    }                   
                }             
            }catch(HeadlessException ex){
                Logger.getLogger(Analizer.class.getName()).log(Level.SEVERE, null, ex);
            }
            cadena = cadena.replace("","");
            cadena = cadena.replace("<html>","");
            cadena = cadena.replace("<head>","");
            cadena = cadena.replace("</head>","");
            cadena = cadena.replace("<body","");
            //cadena = cadena.replace("<p style = \ margin-top:>","");
            cadena = cadena.replace("<br","");
            cadena = cadena.replace("&#161","¡");
            cadena = cadena.replace("","");
            cadena = cadena.replace("&#191","¿");
            cadena = cadena.replace("&#176","°");
            cadena = cadena.replace("&#172","¬");
            cadena = cadena.replace("&amp","&");
            cadena = cadena.replace("</p>","");
            cadena = cadena.replace("</html>","");
            cadena = cadena.replace("</body>","");
            cadena = cadena.replace("&quot", "/");
                        
            StringReader SR = new StringReader(cadena);
            BufferedReader BR = new BufferedReader(SR);
                        
            //Lexer scanl = new Lexer (BR);
            //Symbol sim = scanl.next_token();
            int contlinea = 0;
            texto += (contlinea++)+" ";
            //en esta parte va el while con los colores
            texto = "</p></body></html>";
            epscript.setContentType("text/html");
            epscript.setText(texto);
        }catch(Exception e){
            Logger.getLogger(Analizer.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }//GEN-LAST:event_btnrecargarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnarchivoevaluadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarchivoevaluadoActionPerformed
        String rutal = txt_path.getText();
	File f = new File (rutal);
	if (f.exists()){
		try{
			Runtime.getRuntime().exec("rund1132 url.dll, FileProtocolHandler "+rutal);
		} catch (Exception e){
			JOptionPane.showMessageDialog(this, e);
		}
	}
	else{
		JOptionPane.showMessageDialog(this, "Archivo pendiente de abrir \n"+rutal, "ERROR", JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_btnarchivoevaluadoActionPerformed

    private void btncargararchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargararchivoActionPerformed
        this.dispose();
	Analizer al = new Analizer();
	al.setResizable(false);
	al.setVisible(true);
    }//GEN-LAST:event_btncargararchivoActionPerformed

    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
        String rutal = "salida.txt";
	File f = new File (rutal);
	if (f.exists()){
		try{
			Runtime.getRuntime().exec("rund1132 url.dll, FileProtocolHandler "+rutal);
		} catch (Exception e){
			JOptionPane.showMessageDialog(this, e);
		}
	}
	else{
		JOptionPane.showMessageDialog(this, "Archivo pendiente de abrir \n"+rutal, "ERROR", JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_btnreporteActionPerformed
    
    TableRowSorter tra = null;
    private void txt_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtroKeyTyped
        DefaultTableModel tokens = (DefaultTableModel) Tabla1.getModel();

	try{
		txt_filtro.addKeyListener(new KeyAdapter(){
                    
		//@Override
		public void KeyReleased(final KeyEvent ke){
			tra.setRowFilter(RowFilter.regexFilter(txt_filtro.getText(), 0));
		}
		});
		tra = new TableRowSorter(tokens);
		Tabla1.setRowSorter(tra);
	}catch(Exception e){
	};
    
    }//GEN-LAST:event_txt_filtroKeyTyped

    private void txt_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pathActionPerformed

    private void txt_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filtroActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton btnarchivoevaluado;
    private javax.swing.JButton btncargararchivo;
    private javax.swing.JButton btnrecargar;
    private javax.swing.JButton btnreporte;
    private javax.swing.JButton btnsalir;
    private javax.swing.JEditorPane epscript;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_filtro;
    private javax.swing.JTextField txt_path;
    // End of variables declaration//GEN-END:variables
}
